version: '3.7'

# 컴퓨터들
services:
  # 컴퓨터이름
  wisc-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/wisc/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker

  # 컴퓨터이름
  wisc-database: # mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'wisc-database'
      MYSQL_ROOT_PASSWORD: '1324'
    ports:
      - 3306:3306

  wisc-redis:
    image: redis:latest
    ports:
      - 6379:6379
